/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        this.setSize(675,400);
        setLocationRelativeTo(this);
        Koneksi.Database.KoneksiDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        Master = new javax.swing.JMenu();
        MSupplier = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        MKaryawan = new javax.swing.JMenuItem();
        Transaksi = new javax.swing.JMenu();
        TFPB = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        Laporan = new javax.swing.JMenu();
        LaporanPermintaan = new javax.swing.JMenuItem();
        Keluar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Pemesanan Barang");
        setBackground(new java.awt.Color(255, 255, 255));

        jMenuBar1.setName("12"); // NOI18N

        Master.setText("Data Master");
        Master.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        MSupplier.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MSupplier.setText("Entry Data Barang");
        MSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MSupplierActionPerformed(evt);
            }
        });
        Master.add(MSupplier);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem2.setText("Entry Data Supplier");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Master.add(jMenuItem2);

        MKaryawan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MKaryawan.setText("Entry Data Karyawan");
        MKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MKaryawanActionPerformed(evt);
            }
        });
        Master.add(MKaryawan);

        jMenuBar1.add(Master);

        Transaksi.setText("Data Transaksi");
        Transaksi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        TFPB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TFPB.setText("Form Permintaan Barang (FPB)");
        TFPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFPBActionPerformed(evt);
            }
        });
        Transaksi.add(TFPB);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem3.setText("Form Pemesanan (SP)");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        Transaksi.add(jMenuItem3);

        jMenuBar1.add(Transaksi);

        Laporan.setText("Laporan");
        Laporan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        LaporanPermintaan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LaporanPermintaan.setText("Laporan Permintaan Barang");
        LaporanPermintaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanPermintaanActionPerformed(evt);
            }
        });
        Laporan.add(LaporanPermintaan);

        jMenuBar1.add(Laporan);

        Keluar.setText("Keluar");
        Keluar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KeluarMouseClicked(evt);
            }
        });
        jMenuBar1.add(Keluar);

        setJMenuBar(jMenuBar1);
        jMenuBar1.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 672, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        View.MSupplier b = new View.MSupplier();
        b.setVisible(true);
        setLocationRelativeTo(this);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void KeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KeluarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_KeluarMouseClicked

    private void MSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MSupplierActionPerformed
        View.MBarang b = new View.MBarang();
        b.setVisible(true);
        setLocationRelativeTo(this);
    }//GEN-LAST:event_MSupplierActionPerformed

    private void MKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MKaryawanActionPerformed
        View.MKaryawan b = new View.MKaryawan();
        b.setVisible(true);
        setLocationRelativeTo(this);
    }//GEN-LAST:event_MKaryawanActionPerformed

    private void TFPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFPBActionPerformed
        View.TFPB b = new View.TFPB();
        b.setVisible(true);
        setLocationRelativeTo(this);
    }//GEN-LAST:event_TFPBActionPerformed

    private void LaporanPermintaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanPermintaanActionPerformed
        View.LapPermintaan p = new View.LapPermintaan();
        p.setVisible(true);
        setLocationRelativeTo(this);
    }//GEN-LAST:event_LaporanPermintaanActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        View.TSP b = new View.TSP();
        b.setVisible(true);
        setLocationRelativeTo(this);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Keluar;
    private javax.swing.JMenu Laporan;
    private javax.swing.JMenuItem LaporanPermintaan;
    private javax.swing.JMenuItem MKaryawan;
    private javax.swing.JMenuItem MSupplier;
    private javax.swing.JMenu Master;
    private javax.swing.JMenuItem TFPB;
    private javax.swing.JMenu Transaksi;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables
}
